### ISSUE TITLE
Parte de Listado Xxx

### ISSUE THREAD

**Issue by Moroswag47** [99effy/tp-covid19#2]
Ya se puede trabajar en el void Listado no? Seria agregar a los sewt los datos necesarios.
El tvrPais lo podemos hacer a partir de lo que pongamos en Listado. Los llamamos como argumento y hacemos la parte de las cuentas totales y porcentajes finales.

**Comment by 99effy** [comment]
Como prefieras, en mi opinión podría no usarse un tvrPais siquiera, pero la duda es si el profe lo aprueba o no.
Si tenés ganas de armar algo, podés hacer un branch nuevo y luego hacer un pull request.
Si no tenés ganas de usar git, simplemente bajá el repo y pasame el código cuando lo termines.
Sino podemos hacerlo juntos, pero ya hoy no estoy disponible.

**Comment by Moroswag47** [comment]
Versión final funcional 100%.
